name = "ecosystem"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hangmen-words"
database_id = "581e7a90-677d-44c5-b573-2b3425928f03"
